In [31]:
import numpy as np
from sklearn.datasets import make_regression

In [32]:
X, y = make_regression(n_samples = 10000)
print(X.shape, y.shape)

(10000, 100) (10000,)


In [33]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

reg = LinearRegression().fit(X, y)
print(mean_squared_error(y, reg.predict(X)))
mse_lr = mean_squared_error(y, reg.predict(X))
reg.coef_

1.9649258543139143e-25


array([ 1.17165748e-14,  8.49848141e+00, -1.24344979e-14, -4.26325641e-14,
       -3.55271368e-14, -1.42108547e-14,  3.73034936e-14,  9.41469125e-14,
        9.94759830e-14, -4.70734562e-14, -3.44169138e-14,  2.06047317e+00,
       -3.10862447e-15,  5.68434189e-14,  6.66133815e-15, -8.65973959e-15,
        7.68274333e-14,  1.33226763e-15, -4.70734562e-14,  2.66453526e-14,
        1.86517468e-14,  2.33146835e-14, -5.95079541e-14,  7.50510765e-14,
       -1.77635684e-15, -2.66453526e-14,  1.24232675e+00,  4.57411886e-14,
       -6.17284002e-14, -2.93098879e-14, -2.66453526e-14, -9.21485110e-14,
        2.53130850e-14,  3.78586051e-14, -1.73194792e-14, -1.59872116e-14,
        5.19584376e-14, -6.08402217e-14,  2.24265051e-14, -1.42108547e-14,
        7.10542736e-15,  7.99360578e-15,  4.68514116e-14, -1.06581410e-14,
        4.17443857e-14,  5.76205750e-14, -8.88178420e-15, -1.24344979e-14,
        1.86517468e-14,  3.99680289e-14,  4.79616347e-14,  5.15143483e-14,
        3.04201109e-14, -

In [34]:
from sklearn.linear_model import SGDRegressor
reg = SGDRegressor(alpha=0.00000001).fit(X, y)
print(mean_squared_error(y, reg.predict(X)))
reg.coef_

2.636399770502014e-12


array([ 7.22169037e-10,  8.49848128e+00,  4.86878603e-09, -4.54742835e-09,
       -5.15954480e-08, -1.20798503e-08,  6.32997830e-09,  2.72372458e-08,
       -5.24985698e-08,  1.04736326e-08,  5.65644844e-09,  2.06047318e+00,
       -2.62468179e-08, -3.40183184e-08, -3.25077306e-08, -1.27810752e-08,
       -4.98927800e-08, -1.05170541e-08, -7.92504099e-09,  4.19742303e-08,
        4.48007234e-08, -4.04592835e-08, -2.24113825e-09, -2.80491621e-08,
       -3.97917660e-08,  1.90763280e-08,  1.24232677e+00, -3.21758048e-10,
       -1.58536398e-08,  1.53130037e-08,  4.25664120e-08, -2.82739786e-08,
       -9.03270073e-10,  3.30930245e-09,  6.76207787e-09,  1.45511738e-08,
        1.73293625e-09, -2.94432879e-08, -9.33066333e-09,  5.87388978e-08,
       -4.10548343e-08,  2.48008419e-09,  1.23832736e-08, -7.03234528e-09,
       -2.45398186e-09, -3.91827775e-08,  1.48582918e-09,  2.79700866e-08,
        1.28879480e-08,  4.54728370e-09, -2.47559418e-08,  1.37848606e-08,
        2.21782395e-08,  

Задание 1 (0.5 балла). make_regression изначально создает линейную проблему, поэтому LinearRegression хорошо ее предсказывает. Также alpha гиперпараметр подобран ПЛОХО.

Задание 2 (0.5 балла).

In [35]:
const = abs(mean_squared_error(y, reg.predict(X)) - mse_lr)
print(const)

2.636399770501818e-12


In [39]:
const = abs(mean_squared_error(y, reg.predict(X)) - mse_lr)

for alph in range(1000):
    reg = SGDRegressor(alpha=1/(10**(alph))).fit(X, y)
    a = abs(mean_squared_error(y, reg.predict(X)) - mse_lr)                  
    if a < const:
        num = alph                   
        const = a
print(const, num, 1/(10**(num)))

3.991213557809933e-26 132 1e-132


In [40]:
reg = LinearRegression().fit(X, y)
print(mean_squared_error(y, reg.predict(X)))

1.9649258543139143e-25


In [41]:
reg = SGDRegressor(alpha=1e-132).fit(X, y)
print(mean_squared_error(y, reg.predict(X)))

8.000499440940884e-25


Был подобран гиперпараметр alpha = 1e-132 методом перебора порядков.

Задание 3 (4 балла)

In [264]:
def MSE(a, b):
    return 1 / a.shape[0] * (a - b).dot(a - b) 

In [307]:
class LinearRegression(object):
    def __init__(self, alpha=0.1, l_ratio=0.001, tol=0.00000001, max_iter=200000):
        '''
        Для начала необходимо инициализировать параметры
        alpha - это learning rate или шаг обучения
        l_ratio - параметр регуляризации
        tol - значение для критерия останова
        max_iter - максимальное количество итераций обучения
        '''
        self.alpha = alpha
        self.l_ratio = l_ratio
        self.tol = tol
        self.max_iter = max_iter
             
    def fit(self, X, y):
        '''
        Метод для обучения линейной регрессии
        X - матрица признаков
        y - вектор правильных ответов
        '''
        
        w = np.ones(X.shape[1])
        b = np.ones(y.shape[0])
        
        for _ in range(self.max_iter): 
            y_pred = X.dot(w) + b
            
            w_1 = w
            y_pred_1 = y_pred
            X_1 = X
            b_1 = b
            
            w_gradient = 2 / y.shape[0] * ((y_pred - y).dot(X))
            b_gradient = 2 / y.shape[0] * np.mean(y_pred - y)
            
            
            w = w - self.alpha * w_gradient
            b = b - self.alpha * b_gradient
            
            
            if abs(MSE(X_1.dot(w_1) + b_1, y) - MSE(X.dot(w) + b, y)) < self.tol:
                break
                
        self.w = w
        self.b = b[0]
   
    def predict(self, X):
        '''
        Метод для предсказаний линейной регрессии
        X - матрица признаков
        '''
        return X.dot(self.w) + self.b
        

In [308]:
my_reg = LinearRegression()
my_reg.fit(X, y)

#mmse = MSE(y, my_reg.predict(X))
#for alpha in range(10, 10000, 100):
#    for max_iter in range(10000, 10000000, 50000):
#        my_reg = LinearRegression(alpha = 1 / alpha, max_iter = max_iter)
#        my_reg.fix(X, y)
#        if MSE(y, my_reg.predict(X)) < mmse:
#            mmse = MSE(y, my_reg.predict(X))
#            mmax_iter = max_iter
#            malpha = alpha
#        if mmse < 1e-3:
#            break
#print(malpha, mmax_iter)
    
        
        
assert mean_squared_error(y, my_reg.predict(X)) < 1e-3
print('You are amazing! Great work!')

You are amazing! Great work!


Ну и вот за 3 часа подбора параметров вплоть до миллиона итераций(в этом случае ошибка была 1e-18) остановился на этих....... Хотел даже на ночь оставить этот подбор параметров(не проверял может он неверно написан, писал его когда ждал миллион итераций) но повезло))))

*Задание 4 (2 балла)*. Добавьте l1 (первый и второй варианты) или l2 (третий и четвертый варианты) регуляризацию.

-------------

In [497]:
def MSE(a, b):
        return 1 / a.shape[0] * (a - b).dot(a - b)

In [691]:
class LinearRegression(object):
    def __init__(self, alpha=0.3, l_ratio=0.00000001, tol=0.0000001, max_iter=60000):
        '''
        Для начала необходимо инициализировать параметры
        alpha - это learning rate или шаг обучения
        l_ratio - параметр регуляризации
        tol - значение для критерия останова
        max_iter - максимальное количество итераций обучения
        '''
        self.alpha = alpha
        self.l_ratio = l_ratio
        self.tol = tol
        self.max_iter = max_iter
        
             
    def fit(self, X, y):
        '''
        Метод для обучения линейной регрессии
        X - матрица признаков
        y - вектор правильных ответов
        '''
        
        w = np.ones(X.shape[1])
        b = np.ones(y.shape[0])
        
        for _ in range(self.max_iter): 
            
            y_pred = X.dot(w) + b
            
            w_1 = w
            y_pred_1 = y_pred
            X_1 = X
            b_1 = b
            
            w_gradient = 2 / y.shape[0] * ((y_pred - y).dot(X)) + 2 * self.l_ratio * w
            b_gradient = 2 / y.shape[0] * np.mean(y_pred - y)
            
            
            w = w - self.alpha * w_gradient
            b = b - self.alpha * b_gradient
            
            
            if abs(MSE(X_1.dot(w_1) + b_1, y) - MSE(X.dot(w) + b, y)) < self.tol:
                break
                
        self.w = w
        self.b = b[0]
   
    def predict(self, X):
        '''
        Метод для предсказаний линейной регрессии
        X - матрица признаков
        '''
        return X.dot(self.w) + self.b
        

In [692]:
my_reg = LinearRegression()
my_reg.fit(X, y)
assert mean_squared_error(y, my_reg.predict(X)) < 1e-3
print('You are amazing! Great work!')

You are amazing! Great work!


*Задание 5 (1 балл)*. Обучите линейную регрессию из коробки

In [385]:
from sklearn.linear_model import Ridge
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [516]:
X, y = make_regression(n_samples = 10000)
reg = LinearRegression()

In [758]:
reg.fit(X, y)
y_pred = Ridge(alpha=0.01).fit(X, y).predict(X)
print(f"MSE: {mean_squared_error(y, y_pred)}")

[0.99940394 0.99940394 0.99940394 ... 0.99940394 0.99940394 0.99940394]
[[ 7.51231274e-01  2.55234470e-01 -1.43850828e+00 ... -6.91283068e-01
   4.29036998e-01 -1.12316699e+00]
 [ 1.08680982e+00  2.76458472e-01  1.12719449e+00 ... -1.12173464e-01
  -3.43447635e-02  2.96581951e-01]
 [ 1.25643090e+00 -4.72871141e-01  2.41187103e-01 ... -1.74057336e+00
   1.46462092e-01  6.89595389e-01]
 ...
 [-1.18261091e+00 -1.69532729e-01  4.96557727e-02 ... -2.38959626e+00
  -9.66144717e-01  1.45202096e+00]
 [ 4.21749448e-01 -1.93843762e+00 -2.14314614e+00 ... -1.44421201e-01
   1.03129093e+00 -9.25627507e-01]
 [-6.55126695e-04  3.75008773e-01 -1.01075317e+00 ...  3.53360614e-01
   2.06782539e-01 -1.56771741e+00]]
[-5.39116446e-02 -2.58098241e-02 -5.34491102e-03 -4.69010973e-02
  3.47697626e+01 -4.15015073e-02  4.44534164e-02 -2.87032483e-02
 -1.28880455e-02 -5.03057398e-03  7.86638109e+01  8.71601990e-03
  3.22457222e+01 -4.57527247e-02 -1.99472032e-03  2.46366878e-02
  1.13904094e-02 -3.90471106e-02

In [755]:
class LinearRegression(object):
    def __init__(self, alpha=0.03, l_ratio=0.01, tol=0.0001, max_iter=1000):
        '''
        Для начала необходимо инициализировать параметры
        alpha - это learning rate или шаг обучения
        l_ratio - параметр регуляризации
        tol - значение для критерия останова
        max_iter - максимальное количество итераций обучения
        '''
        self.alpha = alpha
        self.l_ratio = l_ratio
        self.tol = tol
        self.max_iter = max_iter
        
             
    def fit(self, X, y):
        '''
        Метод для обучения линейной регрессии
        X - матрица признаков
        y - вектор правильных ответов
        '''
        
        w = np.ones(X.shape[1])
        b = np.ones(y.shape[0])
        
        for _ in range(self.max_iter): 
            
            y_pred = X.dot(w) + b
            
            w_1 = w
            y_pred_1 = y_pred
            X_1 = X
            b_1 = b
            
            w_gradient = 2 / y.shape[0] * ((y_pred - y).dot(X)) + 2 * self.l_ratio * w
            b_gradient = 2 / y.shape[0] * np.mean(y_pred - y)
            
            w = w - self.alpha * w_gradient
            b = b - self.alpha * b_gradient
            
            if abs(MSE(X_1.dot(w_1) + b_1, y) - MSE(X.dot(w) + b, y)) < self.tol:
                break
                
        self.w = w
        self.b = b[0]
        
    def predict(self, X):
        '''
        Метод для предсказаний линейной регрессии
        X - матрица признаков
        '''
        return X.dot(self.w) + self.b
        
        

In [756]:
my_reg = LinearRegression()
my_reg.fit(X, y)
print(mean_squared_error(y, my_reg.predict(X)))

213
3.068044135254378
